FlipsideCrypto/polygon-models

- models/silver/silver__blocks.yml
missing blocks ticketed with [PL-117](https://team-1612274056224.atlassian.net/browse/PL-117)
> turn off tests

- models/silver/silver__transactions.yml
- The sequence gap test has changed to throw an error if it is only >10
> change sequence gap test

- dbt_project.yml
- macros/create_sps.sql
- macros/create_udfs.sql
- Polygon (updating for all EVM)
- Added project level variable and associated IF statements to on-run-start macros to default UDF/SP updates to False, preventing macros from being created on every dbt run, unless required (e.g. set UPDATE_UDFS_AND_SPS: True)
- [Jira Ticket](https://team-1612274056224.atlassian.net/browse/AN-2390?atlOrigin=eyJpIjoiOWM2NTUyNDg4ZmQ5NDFhZmI3OTBmMjBhNmZmZjJkN2IiLCJwIjoiaiJ9)
> AN-2390/update-vars-udf-sp-polygon

- README.md
- updated README to include info on project lvl vars (update udfs and sps)
- [Jira Ticket](https://team-1612274056224.atlassian.net/browse/AN-2418)
> AN-2418/readme-vars-polygon

- models/silver/ABIs/silver__contract_proxies.sql
-add next block for proxy contracts if multiple
> add next block

- .gitignore
- macros/tests/tx_block_count.sql
- models/silver/silver__logs.sql
- models/silver/silver__logs.yml
- models/silver/silver__traces.sql
1. Added tx_gaps test to `silver_logs`
2. Changed unique key to tx_hash in `silver_logs` and `silver_traces`
> AN-2583/unique-key-tx-test

- README.md
- dbt_project.yml
- macros/tags/add_database_or_schema_tags.sql
- macros/tags/snowflake_tagging.sql
- models/sushi/sushi__dim_dex_pools.sql
- models/sushi/sushi__dim_kashi_pairs.sql
- models/sushi/sushi__ez_borrowing.sql
- models/sushi/sushi__ez_lending.sql
- models/sushi/sushi__ez_swaps.sql
1. Implemented Snowflake tags via Macros and Model configs
2. Set `UPDATE_SNOWFLAKE_TAGS: True` and updated `readme.md` accordingly
3. Need to run `dbt run-operation` after merge
4. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2699?atlOrigin=eyJpIjoiMjBkNWI3ZTUyN2M4NDI4YzkzNDliYzRiOTZkNzExMGYiLCJwIjoiaiJ9)
> AN-2699/snowflake-tags-polygon

- macros/sp_create_prod_clone.sql
1. Updated `sp_create_prod_clone` with new format/process 
2. Added var to fix issue with snowflake tagging on dev
3. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2728?atlOrigin=eyJpIjoiYjNiODU0ODFmMDlkNDIxMGI2ZmQ4NTI2MjE5MjkzMjciLCJwIjoiaiJ9)
> AN-2728/dev-tag-fix-polygon

- .github/workflows/dbt_docs_update.yml
- .github/workflows/dbt_run_adhoc.yml
- .github/workflows/dbt_run_api_feeder_table.yml
- .github/workflows/dbt_run_dev_refresh.yml
- .github/workflows/dbt_run_incremental.yml
- .github/workflows/dbt_run_streamline_traces_receipts_history.yml
- .github/workflows/dbt_run_streamline_tx_blocks.yml
- .github/workflows/dbt_run_streamline_tx_history.yml
- .github/workflows/dbt_test.yml
1. Modified workflows to reference `environment variables` instead of `secrets` for non-sensitive variables
2. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2756)
> AN-2756/env-var-update

- .github/workflows/dbt_run_abis_temp.yml
- builds a temp workflow to hit the abi pipeline faster
> crank abi pipeline

- models/sushi/sushi__dim_kashi_pairs.yml
- models/sushi/sushi__ez_borrowing.yml
- models/sushi/sushi__ez_lending.yml
1. Added `Deprecating soon` to core sushi model descriptions
2. Removed tests from applicable yml files
> AN-2785/sushi-tests-polygon

- .github/workflows/dbt_run_streamline_decoder.yml
- models/silver/abis/silver__user_verified_abis.sql
- models/silver/silver__decoded_logs.sql
- models/silver/silver__decoded_logs.yml
- models/silver/streamline/decoder/streamline__complete_decode_logs.sql
- models/silver/streamline/decoder/streamline__decode_logs_realtime.sql
- models/sources.yml
- adds realtime polygon decoding pipeline
- edits workflow job 
- tweaks user verification model
> An 2766/realtime decoder

- .gitignore
- models/silver/streamline/streamline__complete_blocks.sql
- models/silver/streamline/streamline__complete_eth_getBlockReceipts.sql
- models/silver/streamline/streamline__complete_trace_blocks.sql
- models/silver/streamline/streamline__complete_transactions.sql
- recent config changes have missing commas
> AN-2837 Fix configs, add missing partition predicates

- .github/workflows/dbt_run_streamline_decoder_history_10_19m.yml
- .github/workflows/dbt_run_streamline_decoder_history_20_24m.yml
- .github/workflows/dbt_run_streamline_decoder_history_30_34m.yml
- .github/workflows/dbt_run_streamline_decoder_history_35_39m.yml
- .github/workflows/dbt_run_streamline_decoder_history_40m.yml
- models/doc_descriptions/general/deprecation.md
- models/gold/core__ez_decoded_event_logs.sql
- models/gold/core__ez_decoded_event_logs.yml
- models/gold/core__fact_decoded_event_logs.sql
- models/gold/core__fact_decoded_event_logs.yml
- models/gold/core__fact_event_logs.yml
- models/gold/core__fact_transactions.yml
> gold views and docs

- .github/workflows/dbt_run_abis.yml
- renames ABI pipeline 
- moves it to hourly
> rename abi pipeline

- models/silver/abis/silver__user_verified_abis.sql
removes 10 event limit with 100k blocks
> tweak limiter

- models/gold/NFT/core__ez_nft_sales.sql
- models/silver/NFT/silver__seaport_1_1.sql
- models/silver/NFT/silver__seaport_1_1.yml
- models/silver/NFT/silver__seaport_1_4.sql
- models/silver/NFT/silver__seaport_1_4.yml
- models/silver/NFT/silver__seaport_1_5.sql
- models/silver/NFT/silver__seaport_1_5.yml
- added Seaport 1.5 
- modified existing 1.4 based on eth's 1.4
- removed recency for 1.4
> An 3218/Seaport 1.5 for Polygon

- models/silver/silver__decoded_logs.sql
- updates unique key to match `silver__logs`
> match logs

- models/silver/core/silver__confirmed_blocks.sql
- adds silver model for testing against
> add confirmed blocks model

- models/silver/core/silver__blocks.sql
- models/silver/core/silver__logs.sql
- models/silver/core/silver__receipts.sql
- models/silver/core/silver__traces.sql
- models/silver/core/silver__transactions.sql
- models/silver/dex/balancer/silver_dex__balancer_pools.sql
- models/silver/dex/balancer/silver_dex__balancer_swaps.sql
- models/silver/dex/curve/silver_dex__curve_pools.sql
- models/silver/dex/curve/silver_dex__curve_swaps.sql
- models/silver/dex/dodo/silver_dex__dodo_v1_swaps.sql
- models/silver/dex/dodo/silver_dex__dodo_v2_swaps.sql
- models/silver/dex/fraxswap/silver_dex__fraxswap_pools.sql
- models/silver/dex/fraxswap/silver_dex__fraxswap_swaps.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v1_dynamic_pools.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v1_dynamic_swaps.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v1_static_pools.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v1_static_swaps.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v2_elastic_pools.sql
- models/silver/dex/kyberswap/silver_dex__kyberswap_v2_elastic_swaps.sql
- models/silver/dex/quickswap/silver_dex__quickswap_v2_pools.sql
- models/silver/dex/quickswap/silver_dex__quickswap_v2_swaps.sql
- models/silver/dex/quickswap/silver_dex__quickswap_v3_swaps.sql
- models/silver/dex/sushi/silver_dex__sushi_pools.sql
- models/silver/dex/sushi/silver_dex__sushi_swaps.sql
- models/silver/dex/uniswap/silver_dex__univ3_pools.sql
- models/silver/dex/uniswap/silver_dex__univ3_swaps.sql
- models/silver/dex/woofi/silver_dex__woofi_swaps.sql
- models/silver/silver__nft_transfers.sql
- models/silver/silver__transfers.sql
- Update all models using hex_to_int using `public` or `ethereum.public` schema to `utils` schema
- Excludes models with `enabled = false`
- Was having issues running models with `ALTER TABLE {{ this }} ADD SEARCH OPTIMIZATION` post hook
- After setting all post hooks from `ALTER TABLE {{ this }} ADD SEARCH OPTIMIZATION`  to `""` all models ran successfully
- Did not commit post_hook modifications, only used for testing
> AN-3306/swap-public-to-utils

- .github/workflows/dbt_test_daily.yml
- .github/workflows/dbt_test_intraday.yml
- .github/workflows/dbt_test_monthly.yml
- macros/tests/missing_txs.sql
- Update environment name
- Create monthly test yml
- Update traces test block exclude
> An 3575/full-test-updates

- models/silver/silver__nft_transfers.sql
Removing nft transfers where 0 nfts are transferred but appears on logs
> add erc1155 value filter

- models/deploy/core/_utils.yml
Reverts FlipsideCrypto/polygon-models#257
> Revert "Remove version to match LQ models"

- models/deploy/core/_utils.yml
Reverts FlipsideCrypto/polygon-models#259
> Revert "Temp delete utils test"

- .github/workflows/dbt_run_dummy.yml
- models/silver/utilities/silver__dummy_workflow.sql
dummy workflow for LiveQuery action triggering testing
> dummy workflow

- macros/actions/trigger_dummy_gha.sql
- sets task result with last status code for testing purposes
> set result

- .github/workflows/dbt_run_abi_refresh.yml
- .github/workflows/dbt_run_full_observability.yml
- .github/workflows/dbt_run_heal_models.yml
- .github/workflows/dbt_run_incremental_non_realtime.yml
- .github/workflows/dbt_run_operation_reorg.yml
- .github/workflows/dbt_run_streamline_chainhead.yml
- .github/workflows/dbt_run_streamline_decoder.yml
- .github/workflows/dbt_run_streamline_decoder_history_range_1.yml
- .github/workflows/dbt_run_streamline_decoder_history_range_2.yml
- .github/workflows/dbt_run_streamline_decoder_history_range_3.yml
- .github/workflows/dbt_run_streamline_decoder_history_range_4.yml
- .github/workflows/dbt_run_streamline_decoder_history_range_5.yml
- .github/workflows/dbt_run_streamline_history_adhoc.yml
- .github/workflows/dbt_test_daily.yml
- .github/workflows/dbt_test_intraday.yml
- .github/workflows/dbt_test_monthly.yml
- specify `polygon_models` for dbt tags
> polygon models

- models/silver/NFT/silver__complete_nft_sales.sql
1. Recognise Dew as platform name, 
2. Add aggregator logic
> add platform and aggregator

- models/silver/NFT/silver__nft_transfers.sql
- models/silver/NFT/silver__nft_transfers.yml
add self heal contract logic 
add lookback
> contract self heal logic

- models/silver/NFT/silver__complete_nft_sales.sql
- models/silver/NFT/silver__nft_transfers.sql
> change heal logic

- models/doc_descriptions/general/__overview__.md
- models/doc_descriptions/stats/evm_stats_core.md
- models/gold/stats/stats__ez_core_metrics_hourly.sql
- models/gold/stats/stats__ez_core_metrics_hourly.yml
- models/silver/stats/silver_stats__core_metrics_hourly.sql
- models/silver/stats/silver_stats__core_metrics_hourly.yml
1. Aggregated stats table for core metrics hourly
2. Requires permissions for new schema
`dbt run -m models/silver/stats+ --full-refresh`
> AN-4454/core-stats

- models/silver/defi/lending/aave/silver__aave_tokens.sql
- models/silver/defi/lending/aave/silver__aave_tokens.yml
`dbt run -m models/silver/defi/lending/aave/silver__aave_tokens.sql --full-refresh`
> AN-4556/add-aave-token-model-tests 

- models/silver/defi/lending/aave/silver__aave_tokens.sql
`dbt run -m models/silver/defi/lending/aave/silver__aave_tokens.sql --full-refresh`
> aave_token_fix_2 

- models/bronze/api_udf/bronze_api__contract_abis.sql
- models/bronze/api_udf/bronze_api__token_reads.sql
- models/silver/defi/bridge/hop/silver_bridge__hop_ammwrapper.sql
- models/silver/defi/bridge/hop/silver_bridge__hop_l2canonicaltoken.sql
- models/silver/defi/bridge/stargate/silver_bridge__stargate_createpool.sql
- models/silver/defi/dex/balancer/silver_dex__balancer_pools.sql
- models/silver/defi/dex/curve/silver_dex__curve_pools.sql
- models/sources.yml
- package-lock.yml
- packages.yml
`dbt run -s livequery_models.deploy.core --vars '{DROP_UDFS_AND_SPS: true}' -t prod && dbt run -s livequery_models.deploy.core --vars '{UPDATE_UDFS_AND_SPS: true}' -t prod`
> vault secrets

- models/silver/NFT/sales/silver__aggregator_list.sql
- models/silver/NFT/sales/silver__complete_nft_sales.sql
`dbt run -m models/silver/NFT/sales/silver__aggregator_list.sql --full-refresh && dbt run -m models/silver/NFT/sales/silver__complete_nft_sales.sql --vars '{"HEAL_MODEL":True}'`
> add aggregator logic

- models/doc_descriptions/transfers/evm_transfers_table_doc.md
- models/doc_descriptions/transfers/poly_transfer_table_doc.md
- models/gold/core/core__ez_native_transfers.yml
- models/gold/core/core__ez_token_transfers.yml
- models/gold/core/core__fact_token_transfers.yml
to capture docs updates in snowflake: `dbt run -m models/gold/core/core__ez_native_transfers.sql models/gold/core/core__ez_token_transfers.sql models/gold/core/core__fact_token_transfers.sql`
> AN-4879/transfers-docs

- models/gold/NFT/nft__ez_nft_sales.yml
- models/silver/NFT/sales/silver__complete_nft_sales.sql
- models/silver/NFT/sales/silver__element_sales.sql
- models/silver/NFT/sales/silver__element_sales.yml
- models/silver/NFT/sales/silver__mooar_sales.sql
- models/silver/NFT/sales/silver__seaport_1_1_sales.sql
- models/silver/NFT/sales/silver__seaport_1_4_sales.sql
- models/silver/NFT/sales/silver__seaport_1_5_sales.sql
- models/silver/NFT/sales/silver__seaport_1_6_sales.sql
- models/silver/NFT/sales/silver__tofunft_sales.sql
Add element marketplace to polygon
`dbt run -m models/silver/nft/sales/silver__element_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver__complete_nft_sales.sql --vars '{"HEAL_MODELS":["element"]}'`
> An 4749/element poly

- models/silver/NFT/sales/silver__complete_nft_sales.sql
Change MATIC to POL after Sept 4 for nft sales
`update polygon.silver.complete_nft_sales 
set currency_address = 'POL'
where currency_address = 'MATIC'
and block_timestamp::date >= '2024-09-04'`
> An 5169/matic to pol nft

- models/silver/protocols/polymarket/silver__polymarket_filled_orders.sql
- models/silver/protocols/polymarket/silver__polymarket_filled_orders.yml
- models/sources.yml
`dbt run -m models/silver/protocols/polymarket`
> AN-5227/add-poylmarket-filled-orders

- .github/workflows/dbt_run_traces_fix.yml
- models/silver/core/silver__fact_traces2.sql
- models/silver/core/traces2_fix/silver__fact_traces2_fix.sql
fix the error logic for fact_traces2 and new data
add model to identify historical data that needs fixing
add workflow to run model in step 2
`dbt run -m models/silver/core/traces2_fix/silver__fact_traces2_fix.sql --full-refresh`
> AN-5669 Add traces2 fix - polygon

- models/doc_descriptions/fsc_evm/evm_deprecations.md
- models/doc_descriptions/fsc_evm/nft.md
- models/gold/NFT/nft__ez_nft_mints.sql
- models/gold/NFT/nft__ez_nft_mints.yml
- models/gold/NFT/nft__ez_nft_sales.sql
- models/gold/NFT/nft__ez_nft_sales.yml
- models/gold/NFT/nft__ez_nft_transfers.sql
- models/gold/NFT/nft__ez_nft_transfers.yml
`dbt run -m models/gold/NFT/nft__ez_nft_mints.sql models/gold/NFT/nft__ez_nft_sales.sql models/gold/NFT/nft__ez_nft_transfers.sql --full-refresh`
> Add nft cols poly

- models/bronze/api_udf/bronze_api__contract_abis.sql
update abi api link, secret and path 
delete from polygon.bronze_api.contract_abis
where _inserted_timestamp >= '2025-01-22 00:21:15.914'
> AN-5824/update abi request

- models/silver/defi/lending/compound/silver__comp_asset_details.sql
- models/silver/defi/lending/compound/silver__comp_borrows.sql
- models/silver/defi/lending/compound/silver__comp_deposits.sql
- models/silver/defi/lending/compound/silver__comp_liquidations.sql
- models/silver/defi/lending/compound/silver__comp_repayments.sql
- models/silver/defi/lending/compound/silver__comp_withdraws.sql
`dbt run -m models/silver/defi/lending/compound --full-refresh && dbt run --vars '{"HEAL_MODELS":"comp"}' -m models/silver/defi/lending/complete_lending+`
> AN-6328/update-compv3-asset-details 

- models/silver/defi/lending/aave/silver__aave_tokens.sql
`dbt run -m models/silver/defi/lending/aave --full-refresh && dbt run --vars '{"HEAL_MODELS":"aave"}' -m models/silver/defi/lending/complete_lending`
> AN-5443/aave-token-model-updates

- packages.yml
`dbt seed && dbt run --vars '{"HEAL_MODEL":"True"}' -m "fsc_evm,tag:complete_lending"`
> add-testing-token-seed
